[package]
name = "htmlprep"
version = "0.0.2"
description = "IN-ALPHA: An HTML Pre-Processor for creating static HTML files"
license = "MIT OR Apache-2.0"

edition = "2021"

[dependencies]
regex = "1.8.4"
