[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0.17", features = ["zlib"], default-features = false }
num-digitize = "0.4.2"
# base64 = "0.13.0"
# lazy_static = "1.4.0"
# regex = "1.5.4"
