[package]
name = "htmlprep"
version = "0.0.3"
description = "IN-ALPHA: An HTML Pre-Processor for creating static HTML files"
license = "MIT OR Apache-2.0"
exclude = ["/testdata", "/tests"]
rust-version = "1.70"

edition = "2021"

[dependencies]
regex = "1.8.4"
[dev-dependencies]
tempdir = "0.3"